# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('assets\\app_icon.ico', 'assets'),
        ('assets\\logo.png', 'assets'),
        ('database', 'database'),
        ('email_config.json', '.'),
        ('ui\\inventory.py', 'ui'),
    ],
    hiddenimports=[
        'ui.admin_setup',
        'ui.backup',
        'ui.checkout',
        'ui.dashboard',
        'ui.email_settings',
        'ui.expenses',
        'ui.inventory',
        'ui.login',
        'ui.pos',
        'ui.reports',
        'ui.settings',
        'ui.user_mgmt',
        'ui.vat_settings',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets\\app_icon.ico',
)
