# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('database/__init__.py', 'database'),
        ('database/init_db.py', 'database'),
        ('email_config.json', '.'),
    ],
    hiddenimports=[
        'ui.admin_setup',
        'ui.backup',
        'ui.cart',
        'ui.checkout',
        'ui.dashboard',
        'ui.email_settings',
        'ui.expenses',
        'ui.inventory',
        'ui.login',
        'ui.order_history',
        'ui.pos',
        'ui.reports',
        'ui.settings',
        'ui.shell',
        'ui.uom_settings',
        'ui.user_mgmt',
        'ui.vat_settings',
        'modules.backup',
        'modules.dashboard',
        'modules.expenses',
        'modules.items',
        'modules.notifications',
        'modules.portions',
        'modules.pos',
        'modules.receipts',
        'modules.refunds',
        'modules.reports',
        'modules.units_of_measure',
        'modules.users',
        'modules.variants',
        'modules.vat_rates',
        'utils.csv_io',
        'utils.images',
        'utils.security',
        'database.init_db',
        'tkcalendar',
        'PIL',
        'pycountry',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets\\app_icon.ico',
)
